/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StampDutyCalculatorImport } from './routes/stampDutyCalculator'
import { Route as ServicesImport } from './routes/services'
import { Route as MortgageCalculatorImport } from './routes/mortgageCalculator'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StampDutyCalculatorRoute = StampDutyCalculatorImport.update({
  path: '/stampDutyCalculator',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const MortgageCalculatorRoute = MortgageCalculatorImport.update({
  path: '/mortgageCalculator',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/mortgageCalculator': {
      id: '/mortgageCalculator'
      path: '/mortgageCalculator'
      fullPath: '/mortgageCalculator'
      preLoaderRoute: typeof MortgageCalculatorImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/stampDutyCalculator': {
      id: '/stampDutyCalculator'
      path: '/stampDutyCalculator'
      fullPath: '/stampDutyCalculator'
      preLoaderRoute: typeof StampDutyCalculatorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mortgageCalculator': typeof MortgageCalculatorRoute
  '/services': typeof ServicesRoute
  '/stampDutyCalculator': typeof StampDutyCalculatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mortgageCalculator': typeof MortgageCalculatorRoute
  '/services': typeof ServicesRoute
  '/stampDutyCalculator': typeof StampDutyCalculatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mortgageCalculator': typeof MortgageCalculatorRoute
  '/services': typeof ServicesRoute
  '/stampDutyCalculator': typeof StampDutyCalculatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/mortgageCalculator'
    | '/services'
    | '/stampDutyCalculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/mortgageCalculator'
    | '/services'
    | '/stampDutyCalculator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/mortgageCalculator'
    | '/services'
    | '/stampDutyCalculator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MortgageCalculatorRoute: typeof MortgageCalculatorRoute
  ServicesRoute: typeof ServicesRoute
  StampDutyCalculatorRoute: typeof StampDutyCalculatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MortgageCalculatorRoute: MortgageCalculatorRoute,
  ServicesRoute: ServicesRoute,
  StampDutyCalculatorRoute: StampDutyCalculatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/mortgageCalculator",
        "/services",
        "/stampDutyCalculator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/mortgageCalculator": {
      "filePath": "mortgageCalculator.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/stampDutyCalculator": {
      "filePath": "stampDutyCalculator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
