/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as CalculatorsImport } from './routes/_calculators'
import { Route as IndexImport } from './routes/index'
import { Route as CalculatorsStampDutyCalculatorImport } from './routes/_calculators/stampDutyCalculator'
import { Route as CalculatorsAffordabilityCalculatorImport } from './routes/_calculators/affordabilityCalculator'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsRoute = CalculatorsImport.update({
  id: '/_calculators',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsStampDutyCalculatorRoute =
  CalculatorsStampDutyCalculatorImport.update({
    path: '/stampDutyCalculator',
    getParentRoute: () => CalculatorsRoute,
  } as any)

const CalculatorsAffordabilityCalculatorRoute =
  CalculatorsAffordabilityCalculatorImport.update({
    path: '/affordabilityCalculator',
    getParentRoute: () => CalculatorsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_calculators': {
      id: '/_calculators'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CalculatorsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/_calculators/affordabilityCalculator': {
      id: '/_calculators/affordabilityCalculator'
      path: '/affordabilityCalculator'
      fullPath: '/affordabilityCalculator'
      preLoaderRoute: typeof CalculatorsAffordabilityCalculatorImport
      parentRoute: typeof CalculatorsImport
    }
    '/_calculators/stampDutyCalculator': {
      id: '/_calculators/stampDutyCalculator'
      path: '/stampDutyCalculator'
      fullPath: '/stampDutyCalculator'
      preLoaderRoute: typeof CalculatorsStampDutyCalculatorImport
      parentRoute: typeof CalculatorsImport
    }
  }
}

// Create and export the route tree

interface CalculatorsRouteChildren {
  CalculatorsAffordabilityCalculatorRoute: typeof CalculatorsAffordabilityCalculatorRoute
  CalculatorsStampDutyCalculatorRoute: typeof CalculatorsStampDutyCalculatorRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsAffordabilityCalculatorRoute:
    CalculatorsAffordabilityCalculatorRoute,
  CalculatorsStampDutyCalculatorRoute: CalculatorsStampDutyCalculatorRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof CalculatorsRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/affordabilityCalculator': typeof CalculatorsAffordabilityCalculatorRoute
  '/stampDutyCalculator': typeof CalculatorsStampDutyCalculatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof CalculatorsRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/affordabilityCalculator': typeof CalculatorsAffordabilityCalculatorRoute
  '/stampDutyCalculator': typeof CalculatorsStampDutyCalculatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_calculators': typeof CalculatorsRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/_calculators/affordabilityCalculator': typeof CalculatorsAffordabilityCalculatorRoute
  '/_calculators/stampDutyCalculator': typeof CalculatorsStampDutyCalculatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/contact'
    | '/services'
    | '/affordabilityCalculator'
    | '/stampDutyCalculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/contact'
    | '/services'
    | '/affordabilityCalculator'
    | '/stampDutyCalculator'
  id:
    | '__root__'
    | '/'
    | '/_calculators'
    | '/about'
    | '/contact'
    | '/services'
    | '/_calculators/affordabilityCalculator'
    | '/_calculators/stampDutyCalculator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_calculators",
        "/about",
        "/contact",
        "/services"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_calculators": {
      "filePath": "_calculators.tsx",
      "children": [
        "/_calculators/affordabilityCalculator",
        "/_calculators/stampDutyCalculator"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/_calculators/affordabilityCalculator": {
      "filePath": "_calculators/affordabilityCalculator.tsx",
      "parent": "/_calculators"
    },
    "/_calculators/stampDutyCalculator": {
      "filePath": "_calculators/stampDutyCalculator.tsx",
      "parent": "/_calculators"
    }
  }
}
ROUTE_MANIFEST_END */
